### ISSUE TITLE
Shit code skid

### ISSUE THREAD

**Issue by KASLR** [XorV2/xraq-s-cock#1]
This code is overall really fucking bad. It's not only useless you are hard-coding the arbitrary-length of your second parameter of your fgets() function call. Not to mention this program is straight up not optimized or fast. Takes 700MS++ for the program to actually run. Not to mention, you are also doing ```printf("\n");``` what you can do instead and will actually be faster is to print a single char instead of using a string to print this; like so ```putchar('\n')```. This is not only better looking it's also much faster than calling printf() because printf() is a variadic function meaning it can have an endless amount of parameters for the actual function. ```putchar('\n');``` isn't variadic meaning it'll much less time to actually run and execute than ```printf("\n");``` normally would.

**Comment by XorV2** [comment]
took you 7 months L0L and it doesn't take a genius to figure that out Aiden. not going to lie this was very bad code but there's a reason i didn't comment on it/delete it, because it was 7 months ago L0L
